/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  stocksSidebar: [
    {
      type: 'doc',
      id: 'stocks/introduction1',
      label: '引言一'
    },
    {
      type: 'doc',
      id: 'stocks/introduction2',
      label: '引言二'
    },
  ],
  confuciusSidebar: [
    {
      type: 'doc',
      id: 'confucius/confucius1',
      label: '《论语》详解：给所有曲解孔子的人（一）'
    },
    {
      type: 'doc',
      id: 'confucius/confucius2',
      label: '《论语》详解：给所有曲解孔子的人（二）'
    },
  ]

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;
